group: travis_latest
language: python
cache: pip
python:
  - 3.8


env:
  global:
    # **Customize your credentials and wether skills have to be deployed when building to the main branch**
    - DEPLOY_MAIN_BRANCH=TRUE
    - TRAINING_TIMEOUT_IN_SECONDS=180
    - WA_URL=https://api.us-south.assistant.watson.cloud.ibm.com
    # WA_APIKEY needs to be defined. Use the reppo settings or an encrypted variable


install:
  - pip install https://github.com/xverges/wa-cli/archive/master.zip
  - ./.wa-cli/travis-deploy.sh


script:
  - ./.wa-cli/travis-test.sh


after_script:
  - ./.wa-cli/travis-cleanup.sh
