group: travis_latest
language: python
cache: pip
python:
  - 3.8

#if:
#  type != "pull_request"

env:
  global:
    # **Customize your credentials and wether skills have to be deployed when building to the main branch**
    - DEPLOY_MAIN_BRANCH=TRUE
    - TRAINING_TIMEOUT_IN_SECONDS=180
    - WA_URL=https://api.us-south.assistant.watson.cloud.ibm.com
    # WA_APIKEY needs to be defined. Use the reppo settings or an encrypted variable


install:
  - pip install https://github.com/xverges/wa-cli/archive/master.zip
  - ./.wa-cli/travis-deploy.sh


script:
  - ./.wa-cli/travis-test.sh

after_script:
  - |
    echo "Cleaning up..."
    if [[ -n "${TRAVIS_PULL_REQUEST_BRANCH}" ]]; then
        echo "Deleting the PR sandboxes..."
        while read -r skill; do
            wa-cli sandbox delete "$skill"
        done < skills_to_test.txt
    else
        echo "No ad-hoc PR skills where created for this build"
    fi
